# This is a basic workflow to help you get started with Actions

name: Upload-and-Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      scanName:
        description: 'Name of the Scan'     
        required: true
      sandbox:
        description: 'Sandbox Name'
        required: false  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # zip the code
      - name: package
        run: zip -r artifact.zip . -x ".git/*" ".github/*" "src/test" ".vscode/*" ".vscode-test/*" "releases/*" "media/*" "out/*" "node_modules/*"

      - uses: actions/upload-artifact@v2 
        with:
          path: artifact.zip # See: https://github.com/actions/upload-artifact
          name: package-zip
          
      - name: Echo Branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Print Branch name
        run: echo "${{ steps.extract_branch.outputs.branch }}"

  # This workflow contains a single job called "build"
  Static-Scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [package]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: package-zip

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # appname
          appname: "VSCode-unified"
          # createprofile
          createprofile: false
          # filepath
          filepath: result.zip #Path to dlls/src/jars/wars....
          # version
          version: ${{ github.event.inputs.scanName }}
          # vid
          vid: ${{ secrets.VERACODE_API_ID }}
          # vkey
          vkey: ${{ secrets.VERACODE_API_KEY }}
          # wait X minutes for the scan to complete
          scantimeout: 0
          # business criticality - policy selection
